import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 16,
  },
  titleBar: {
    alignSelf: 'stretch',
    marginHorizontal: -16,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#1e3a8a',
    borderBottomWidth: 1,
    borderBottomColor: '#1d4ed8',
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    color: '#ffffff',
    textAlign: 'center',
  },
  card: {
    width: '65%',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d1d9e6',
    backgroundColor: '#ffffff',
    padding: 14,
    gap: 5,
    marginVertical: 5,
  },
  postsScroll: {
    alignSelf: 'stretch',
    flex: 1,
    marginHorizontal: -16,
  },
  postsContent: {
    alignItems: 'center',
    gap: 14,
    paddingHorizontal: 16,
    paddingBottom: 20,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  username: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  verifiedBadgeImage: {
    width: 20,
    height: 20,
    resizeMode: 'contain' as const,
  },
  verifiedBadgeWrap: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeTooltip: {
    position: 'absolute',
    top: -36,
    right: -52,
    minWidth: 112,
    backgroundColor: '#566077',
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 6,
    alignItems: 'center',
    zIndex: 10,
  },
  badgeTooltipText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
  },
  bodyText: {
    fontSize: 15,
    lineHeight: 22,
    color: '#1e293b',
  },
  moodText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#4f46e5',
  },
  addButton: {
    position: 'absolute',
    left: 16,
    bottom: 18,
    width: 50,
    height: 50,
    borderRadius: 18,
    backgroundColor: '#1e3a8a',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  addIconHorizontal: {
    position: 'absolute',
    width: 20,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#d1d9e6',
  },
  addIconVertical: {
    position: 'absolute',
    width: 4,
    height: 20,
    borderRadius: 2,
    backgroundColor: '#d1d9e6',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#f8fafc',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d1d9e6',
    padding: 20,
    gap: 12,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0f172a',
  },
  modalBody: {
    fontSize: 15,
    lineHeight: 22,
    color: '#334155',
  },
  modalFieldLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#64748b',
    marginTop: 2,
  },
  modalInput: {
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    fontSize: 16,
    color: '#0f172a',
  },
  modalSelectLike: {
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalSelectText: {
    fontSize: 16,
    color: '#0f172a',
  },
  modalSelectArrow: {
    fontSize: 16,
    color: '#334155',
    fontWeight: '700',
  },
  modalTextarea: {
    minHeight: 96,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: '#0f172a',
  },
  modalPrimaryButton: {
    marginTop: 8,
    height: 46,
    borderRadius: 10,
    backgroundColor: '#5b5ce2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalPrimaryButtonWrap: {
    position: 'relative',
  },
  modalPrimaryButtonDisabled: {
    backgroundColor: '#a5b4fc',
  },
  modalPrimaryButtonText: {
    fontSize: 20,
    fontWeight: '800',
    color: '#ffffff',
  },
  modalErrorText: {
    fontSize: 13,
    color: '#b91c1c',
    fontWeight: '600',
  },
  modalHintBubble: {
    position: 'absolute',
    bottom: 58,
    left: '50%',
    transform: [{ translateX: -58 }],
    width: 116,
    backgroundColor: '#0f172a',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 8,
    zIndex: 20,
  },
  modalHintText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  modalCloseButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#1e3a8a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCloseButtonText: {
    color: '#d1d9e6',
    fontSize: 12,
    fontWeight: '800',
  },
});

export default styles;