import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 16,
  },
  titleBar: {
    alignSelf: 'stretch',
    marginHorizontal: -16,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#1e3a8a',
    borderBottomWidth: 1,
    borderBottomColor: '#1d4ed8',
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    color: '#ffffff',
    textAlign: 'center',
  },
  card: {
    width: '85%',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d1d9e6',
    backgroundColor: '#ffffff',
    padding: 14,
    gap: 5,
    marginVertical: 25,
  },
  postsScroll: {
    alignSelf: 'stretch',
    flex: 1,
    marginHorizontal: -16,
  },
  postsContent: {
    alignItems: 'center',
    gap: 14,
    paddingHorizontal: 16,
    paddingBottom: 20,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  username: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  verifiedBadgeImage: {
    width: 20,
    height: 20,
    resizeMode: 'contain' as const,
  },
  verifiedBadgeWrap: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeTooltip: {
    position: 'absolute',
    top: -36,
    right: -52,
    minWidth: 112,
    backgroundColor: '#566077',
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 6,
    alignItems: 'center',
    zIndex: 10,
  },
  badgeTooltipText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
  },
  bodyText: {
    fontSize: 15,
    lineHeight: 22,
    color: '#1e293b',
  },
  moodText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#4f46e5',
  },
  buttonsContainer: {
    width: '100%',
    paddingHorizontal: 12,
    paddingBottom: 20,
  },
  buttonsContainerNarrow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    rowGap: 12,
    columnGap: 8,
  },
  buttonsContainerWide: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    columnGap: 8,
  },
  addButtonGroup: {
    alignItems: 'center',
    position: 'relative',
  },
  dangerButtonGroup: {
    alignItems: 'center',
    position: 'relative',
  },
  refreshButtonGroup: {
    alignItems: 'center',
    position: 'relative',
  },
  buttonGroupNarrow: {
    flexBasis: '48%',
    maxWidth: '48%',
  },
  buttonGroupWide: {
    flex: 1,
    maxWidth: '25%',
  },

  addButton: {
    width: 50,
    height: 50,
    borderRadius: 18,
    backgroundColor: '#1e3a8a',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  refreshButton: {
    width: 50,
    height: 50,
    borderRadius: 18,
    backgroundColor: '#1e3a8a',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  dangerButton: {
    width: 50,
    height: 50,
    borderRadius: 18,
    backgroundColor: '#dc2626',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  refreshButtonText: {
    color: '#d1d9e6',
    fontSize: 24,
    fontWeight: '900',
    lineHeight: 24,
  },
  dangerButtonText: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 28,
  },
  bottomButtonLabel: {
    marginTop: 6,
    width: 120,
    color: '#334155',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  actionTooltipPageCenter: {
    position: 'absolute',
    bottom: '15%',
    left: '50%',
    transform: [{ translateX: -70 }, { translateY: -18 }],
    width: 200,
    backgroundColor: '#0f172a',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 8,
    zIndex: 40,
  },
  actionTooltipText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  addIconHorizontal: {
    position: 'absolute',
    width: 20,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#d1d9e6',
  },
  addIconVertical: {
    position: 'absolute',
    width: 4,
    height: 20,
    borderRadius: 2,
    backgroundColor: '#d1d9e6',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#f8fafc',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d1d9e6',
    padding: 20,
    gap: 12,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0f172a',
  },
  modalBody: {
    fontSize: 15,
    lineHeight: 22,
    color: '#334155',
  },
  modalFieldLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#64748b',
    marginTop: 2,
  },
  modalGuidelinesBox: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#eef2ff',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 2,
  },
  modalGuidelinesTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1e3a8a',
    marginBottom: 2,
  },
  modalGuidelinesText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#334155',
    fontWeight: '600',
  },
  modalInput: {
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    fontSize: 16,
    color: '#0f172a',
  },
  modalSelectLike: {
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalSelectText: {
    fontSize: 16,
    color: '#0f172a',
  },
  modalSelectArrow: {
    fontSize: 16,
    color: '#334155',
    fontWeight: '700',
  },
  modalTextarea: {
    minHeight: 96,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: '#0f172a',
  },
  modalPrimaryButton: {
    marginTop: 8,
    height: 46,
    borderRadius: 10,
    backgroundColor: '#566077',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalPrimaryButtonWrap: {
    position: 'relative',
  },
  modalPrimaryButtonDisabled: {
    backgroundColor: '#8492a8',
  },
  modalPrimaryButtonText: {
    fontSize: 20,
    fontWeight: '800',
    color: '#ffffff',
  },
  modalErrorText: {
    fontSize: 13,
    color: '#b91c1c',
    fontWeight: '600',
  },
  modalHintBubble: {
    position: 'absolute',
    bottom: 58,
    left: '50%',
    transform: [{ translateX: -58 }],
    width: 116,
    backgroundColor: '#0f172a',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 8,
    zIndex: 20,
  },
  modalHintText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  modalCloseButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#1e3a8a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCloseButtonText: {
    color: '#d1d9e6',
    fontSize: 12,
    fontWeight: '800',
  },
  createSuccessPopup: {
    position: 'absolute',
    bottom: 84,
    alignSelf: 'center',
    backgroundColor: '#0f172a',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    zIndex: 30,
  },
  createSuccessPopupText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  learnContainer: {
    flex: 1,
    backgroundColor: '#eef2f7',
  },
  learnTopBar: {
    backgroundColor: '#1e3a8a',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginTop: -1,
    position: 'relative',
    zIndex: 70,
    elevation: 70,
  },
  learnTopTitle: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '800',
  },
  learnTopSpacer: {
    width: 120,
  },
  learnCategoryWrap: {
    width: 140,
    position: 'relative',
    zIndex: 80,
    elevation: 80,
  },
  learnCategoryButton: {
    minHeight: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d5dcea',
    backgroundColor: '#1e3a8a',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
  },
  learnCategoryButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  learnCategoryChevron: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  learnCategoryDropdown: {
    position: 'absolute',
    top: 38,
    left: 0,
    right: 0,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    overflow: 'hidden',
    zIndex: 90,
    elevation: 90,
  },
  learnCategoryItem: {
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  learnCategoryItemText: {
    color: '#1e293b',
    fontSize: 13,
    fontWeight: '600',
  },
  learnScroll: {
    flex: 1,
  },
  learnGrid: {
    alignItems: 'center',
    paddingTop: 12,
    paddingBottom: 24,
  },
  learnCardsContainer: {
    width: '80%',
    alignSelf: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 12,
  },
  learnCard: {
    width: '100%',
    minHeight: 150,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d5dcea',
    backgroundColor: '#ffffff',
    padding: 12,
    justifyContent: 'space-between',
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  learnCardCategory: {
    color: '#4f46e5',
    fontSize: 22,
    fontWeight: '700',
  },
  learnCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  learnCardTitle: {
    color: '#0f172a',
    fontSize: 22,
    lineHeight: 24,
    fontWeight: '800',
    marginTop: 6,
    marginBottom: 10,
  },
  learnCardLink: {
    color: '#0ea5e9',
    fontSize: 18,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  learnVerifiedBadge: {
    marginTop: 8,
    marginBottom: 6,
    alignSelf: 'flex-start',
    backgroundColor: '#eef6ff',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: '#cfe0ff',
  },
  learnVerifiedText: {
    color: '#1e3a8a',
    fontSize: 12,
    fontWeight: '700',
  },
   learnRecommendedSection: {
    width: "100%",
    marginBottom: 12,
    rowGap: 12,

  },

  learnSectionTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 16,
  },

  learnSectionSubtitle: {
    fontSize: 14,
    color: "#6B7280",
    marginBottom: 12,
  },
});

export const tabScreenOptions = {
  tabBarStyle: {
    backgroundColor: '#1e3a8a',
    borderTopColor: '#1e3a8a',
    borderTopWidth: 1,
  },
  tabBarLabelStyle: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600' as const,
  },
  tabBarActiveTintColor: '#ffffff',
  tabBarInactiveTintColor: '#a5b4fc',
  headerShown: true,
  headerStyle: {
    backgroundColor: '#1e3a8a',
    borderBottomColor: '#1e3a8a',
    borderBottomWidth: 1,
  },
  headerTitleStyle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#ffffff',
  },
  headerTintColor: '#ffffff',
};

export default styles;