import { StyleSheet } from 'react-native';

const learnStyles = StyleSheet.create({
  learnContainer: {
    flex: 1,
    backgroundColor: '#eef2f7',
  },
  learnTopBar: {
    backgroundColor: '#1e3a8a',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginTop: -1,
    position: 'relative',
    zIndex: 70,
    elevation: 70,
  },
  learnTopTitle: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '800',
  },
  learnTopSpacer: {
    width: 120,
  },
  learnCategoryWrap: {
    width: 140,
    position: 'relative',
    zIndex: 80,
    elevation: 80,
  },
  learnCategoryButton: {
    minHeight: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d5dcea',
    backgroundColor: '#1e3a8a',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
  },
  learnCategoryButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  learnCategoryChevron: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  learnCategoryDropdown: {
    position: 'absolute',
    top: 38,
    left: 0,
    right: 0,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    overflow: 'hidden',
    zIndex: 90,
    elevation: 90,
  },
  learnCategoryItem: {
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  learnCategoryItemText: {
    color: '#1e293b',
    fontSize: 13,
    fontWeight: '600',
  },
  learnScroll: {
    flex: 1,
  },
  learnGrid: {
    alignItems: 'center',
    paddingTop: 12,
    paddingBottom: 24,
  },
  learnCardsContainer: {
    width: '80%',
    alignSelf: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 12,
  },
  learnCard: {
    width: '49%',
    minHeight: 150,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d5dcea',
    backgroundColor: '#ffffff',
    padding: 12,
    justifyContent: 'space-between',
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  learnCardCategory: {
    color: '#4f46e5',
    fontSize: 22,
    fontWeight: '700',
  },
  learnCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  learnCardTitle: {
    color: '#0f172a',
    fontSize: 28,
    lineHeight: 22,
    fontWeight: '800',
    marginTop: 6,
    marginBottom: 10,
  },
  learnCardLink: {
    color: '#0ea5e9',
    fontSize: 18,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  learnVerifiedBadge: {
    marginTop: 8,
    marginBottom: 6,
    alignSelf: 'flex-start',
    backgroundColor: '#eef6ff',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: '#cfe0ff',
  },
  learnVerifiedText: {
    color: '#1e3a8a',
    fontSize: 12,
    fontWeight: '700',
  },
});

export default learnStyles;
